name: iotclass
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mqtt_client: ^9.8.1
  intl: ^0.18.1
  provider: ^6.0.5
  loading_animations: ^2.2.0
  connectivity_plus: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
     - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/1.png"
  min_sdk_android: 21

flutter_native_splash:
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.
  color: "#1e3d59"
  background_image: "assets/images/1.png"